import PDFDocument from 'pdfkit';
import { TransactionsRow } from '../../../domain/interface/admin-finance-query/transactions';
import { IPdfReportService } from '../../interface/service/IPdfReportService';

export class PdfReportService implements IPdfReportService {
  generateTransactionsPDF(
    rows: TransactionsRow[],
    period: { from: Date; to: Date }
  ): Promise<Buffer> {
    // A wide page so we can fit columns horizontally
    const doc = new PDFDocument({
      size: [900, 1200], // width, height in points
      margins: { top: 60, left: 40, right: 40, bottom: 60 },
    });

    const chunks: Buffer[] = [];
    doc.on('data', c => chunks.push(c));

    let pageNumber = 1;

    // Table columns (tuned widths)
    const columns = [
      { label: 'BookingId', width: 170 },
      { label: 'Event', width: 180 },
      { label: 'Org', width: 100 },
      { label: 'User', width: 100 },
      { label: 'Amount', width: 70 },
      { label: 'Status', width: 80 },
      { label: 'Date', width: 80 },
      { label: 'Method', width: 50 },
    ];

    const startX = doc.page.margins.left;
    const pageInnerWidth =
      doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // Sizes used for pagination/footer logic
    const footerReservedHeight = 80; // reserve space for footer on each page
    const fixedRowHeight = 38; // row height to keep rows consistent

    // ---------- Draw header ----------
    doc
      .font('Helvetica-Bold')
      .fontSize(30)
      .text('EventHub - Transaction Report', {
        align: 'center',
      });

    doc.moveDown(0.8);
    doc
      .font('Helvetica')
      .fontSize(12)
      .text(
        `Report Period: ${period.from.toDateString()} to  ${period.to.toDateString()}`,
        { align: 'left' }
      );
    doc.moveDown(0.1);
    doc.text(`Generated On: ${new Date().toLocaleString()}`, { align: 'left' });

    // set initial cursor Y just under header
    let cursorY = doc.y + 16;

    // ---------- Draw table header function ----------
    const drawTableHeader = () => {
      doc.font('Helvetica-Bold').fontSize(12);
      let x = startX;
      columns.forEach(col => {
        // center small labels better where appropriate
        doc.text(col.label, x, cursorY, { width: col.width, align: 'left' });
        x += col.width;
      });

      cursorY += 18;
      // horizontal rule after header
      doc
        .moveTo(startX, cursorY)
        .lineTo(startX + pageInnerWidth, cursorY)
        .stroke();
      cursorY += 8;
      doc.font('Helvetica').fontSize(11);
    };

    // ---------- Draw footer function (for the current page) ----------
    const drawFooter = () => {
      const footerY =
        doc.page.height - doc.page.margins.bottom - (footerReservedHeight - 20);
      const footerWidth = pageInnerWidth;
      doc.font('Helvetica').fontSize(10);
      doc.text('---- End of Report ----', startX, footerY, {
        width: footerWidth,
        align: 'center',
      });
      doc.text('Generated by EventHub Admin Portal', startX, footerY + 16, {
        width: footerWidth,
        align: 'center',
      });

      // optional page number bottom-left
      const pageNumberText = `Page ${pageNumber}`;
      doc.text(pageNumberText, startX, footerY + 32, {
        width: footerWidth,
        align: 'left',
      });
    };

    // ---------- Start table ----------
    drawTableHeader();

    // space available before we must stop rows on current page (reserve footer)
    const usableBottom =
      doc.page.height - doc.page.margins.bottom - footerReservedHeight;

    for (let i = 0; i < rows.length; i++) {
      const r = rows[i];

      // If we don't have enough space for the next fixed row, finalize page and start new
      if (cursorY + fixedRowHeight > usableBottom) {
        // draw footer for current page
        drawFooter();
        doc.addPage();
        pageNumber++;
        // recalculate pageInnerWidth in case page size changed (but it won't here)
        // reset cursor to top area under header on new page
        // re-draw header on new page (small header)
        doc
          .font('Helvetica-Bold')
          .fontSize(18)
          .text('EventHub - Transaction Report (Continued)', {
            align: 'center',
          });
        doc.moveDown(0.6);
        cursorY = doc.y + 6;
        drawTableHeader();
      }

      // Row data
      let x = startX;
      const values = [
        String(r.bookingId ?? ''),
        String(r.eventTitle ?? ''),
        String(r.organizerName ?? ''),
        String(r.userName ?? ''),
        `INR ${Number(r.totalAmount ?? 0).toLocaleString()}`,
        String(r.status ?? ''),
        new Date(String(r.createdAt)).toLocaleDateString(),
        String(r.paymentMethod ?? ''),
      ];

      // Draw each column with wrapping inside its width
      for (let c = 0; c < columns.length; c++) {
        const col = columns[c];
        doc.text(values[c], x, cursorY, {
          width: col.width,
          ellipsis: true,
          continued: false,
        });
        x += col.width;
      }

      // Move cursor by fixed row height to keep rows consistent (prevents shifting)
      cursorY += fixedRowHeight;
    }

    // After all rows drawn, decide where footer goes:
    // If footer fits on the current page below cursorY, draw it here.
    // Otherwise add a new page and draw footer there.
    if (
      cursorY + footerReservedHeight <=
      doc.page.height - doc.page.margins.bottom
    ) {
      drawFooter();
    } else {
      doc.addPage();
      pageNumber++;
      drawFooter();
    }

    // finalize PDF
    doc.end();

    return new Promise<Buffer>((resolve, reject) => {
      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
      doc.on('error', err => reject(err));
    });
  }
}
